site_name: "ansito"
site_description: "Translate ANSI codes to any other format."
site_url: "https://pawamoy.github.io/ansito"
repo_url: "https://github.com/pawamoy/ansito"
repo_name: "pawamoy/ansito"

nav:
  - Overview: index.md
  - API Reference:
    - cli.py: reference/cli.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/ansito
